In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("data.csv")

In [7]:
df.head()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,2:00,Left-footed shot,Ronaldinho Gaacho
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,3:00,Left-footed shot,NaN
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,2:00,Left-footed shot,Samuel Etoo
3,05/06,LaLiga,19,1/15/06,H,FC Barcelona,Athletic Bilbao,2:01,RW,50,2:01,Left-footed shot,Mark van Bommel
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,2:00,Left-footed shot,Ronaldinho Gaacho

In [8]:
df.tail()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
699,22/23,Ligue 1,21,2/1/23,A,Paris Saint-Germain,Montpellier HSC,1:3,SS,72,0:2,Left-footed shot,Fabián Ruiz
700,22/23,Ligue 1,22,2/4/23,H,Paris Saint-Germain,FC Toulouse,2:1,SS,58,2:1,Left-footed shot,Achraf Hakimi
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,4:3,Direct free kick,\t
702,22/23,Ligue 1,25,2/26/23,A,Paris Saint-Germain,Olympique Marseille,0:3,CF,29,0:2,Right-footed shot,Kylian Mbappé
703,22/23,Ligue 1,26,3/4/23,H,Paris Saint-Germain,FC Nantes,4:2,CF,12,1:0,Left-footed shot,NaN

In [9]:
df.shape

(704, 13)

In [10]:
df.columns

Index(['Season', 'Competition', 'Matchday', 'Date', 'Venue', 'Club',
       'Opponent', 'Result', 'Playing_Position', 'Minute', 'At_score', 'Type',
       'Goal_assist'],
      dtype='str')

In [11]:
df.dtypes

Season              str
Competition         str
Matchday            str
Date                str
Venue               str
Club                str
Opponent            str
Result              str
Playing_Position    str
Minute              str
At_score            str
Type                str
Goal_assist         str
dtype: object

In [13]:
df.describe()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
count,704,704,704,704,704,704,704,704,704,704,704,703,490
unique,19,10,48,455,2,2,98,55,9,97,46,12,71
top,11-Dec,LaLiga,Group Stage,03/07/12,H,FC Barcelona,Sevilla FC,4:00,CF,55,1:00,Left-footed shot,Luis Suarez
freq,73,474,80,5,420,672,38,47,276,14,98,436,48

In [14]:
df.sample()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
353,13/14,LaLiga,36,05-03-14,H,FC Barcelona,Getafe CF,2:02,CF,23,1:00,Left-footed shot,Dani Alves

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            704 non-null    str
 1   Competition       704 non-null    str
 2   Matchday          704 non-null    str
 3   Date              704 non-null    str
 4   Venue             704 non-null    str
 5   Club              704 non-null    str
 6   Opponent          704 non-null    str
 7   Result            704 non-null    str
 8   Playing_Position  704 non-null    str
 9   Minute            704 non-null    str
 10  At_score          704 non-null    str
 11  Type              703 non-null    str
 12  Goal_assist       490 non-null    str
dtypes: str(13)
memory usage: 71.6 KB

In [17]:
df.size

9152

In [18]:
df.ndim

2

In [22]:
df[["Opponent"]]

                 Opponent
0       Albacete Balompie
1    Panathinaikos Athens
2        Racing Santander
3         Athletic Bilbao
4        Deportivo Alaves
..                    ...
699       Montpellier HSC
700           FC Toulouse
701            LOSC Lille
702   Olympique Marseille
703             FC Nantes

[704 rows x 1 columns]

In [27]:
df.loc[[0,5]]

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,2:00,Left-footed shot,Ronaldinho Gaacho
5,05/06,LaLiga,21,1/29/06,A,FC Barcelona,RCD Mallorca,0:03,CF,75,0:02,Right-footed shot,Sylvinho

In [29]:
df.loc[[0,5],["Opponent","Season"]]

            Opponent Season
0  Albacete Balompie  04/05
5       RCD Mallorca  05/06

In [30]:
df[(df["Competition"]=="LaLiga")&(df["Goal_assist"]=="Neymar")]

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
317,13/14,LaLiga,3,09-01-13,A,FC Barcelona,Valencia CF,2:03,CF,41,0:03,Left-footed shot,Neymar
318,13/14,LaLiga,4,9/14/13,H,FC Barcelona,Sevilla FC,3:02,CF,75,2:00,Left-footed shot,Neymar
322,13/14,LaLiga,6,9/24/13,H,FC Barcelona,Real Sociedad,4:01,CF,8,2:00,Header,Neymar
344,13/14,LaLiga,29,3/23/14,A,FC Barcelona,Real Madrid,3:04,CF,42,2:02,Left-footed shot,Neymar
361,14/15,LaLiga,8,10/18/14,H,FC Barcelona,SD Eibar,3:00,CF,74,3:00,Left-footed shot,Neymar
366,14/15,LaLiga,12,11/22/14,H,FC Barcelona,Sevilla FC,5:01,RW,73,4:01,Tap-in,Neymar
367,14/15,LaLiga,12,11/22/14,H,FC Barcelona,Sevilla FC,5:01,RW,78,5:01,Left-footed shot,Neymar
398,14/15,LaLiga,31,04/11-15,A,FC Barcelona,Sevilla FC,2:02,RW,15,0:01,Left-footed shot,Neymar
409,14/15,LaLiga,38,5/23/15,H,FC Barcelona,Deportivo de La Coruaa,2:02,RW,59,2:00,Right-footed shot,Neymar
420,15/16,LaLiga,13,11/28/15,H,FC Barcelona,Real Sociedad,4:00,RW,90+1,4:00,Left-footed shot,Neymar
424,15/16,LaLiga,17,12/30/15,H,FC Barcelona,Real Betis Balompie,4:00,RW,33,2:00,Right-footed shot,Neymar
442,15/16,LaLiga,27,03-03-16,A,FC Barcelona,Rayo Vallecano,1:05,RW,23,0:02,Left-footed shot,Neymar
461,16/17,LaLiga,8,10/15/16,H,FC Barcelona,Deportivo de La Coruaa,4:00,RW,58,4:00,Left-footed shot,Neymar
468,16/17,LaLiga,11,11/06-16,A,FC Barcelona,Sevilla FC,1:02,RW,43,1:01,Left-footed shot,Neymar
471,16/17,LaLiga,13,11/27/16,A,FC Barcelona,Real Sociedad,1:01,RW,59,1:01,Left-footed shot,Neymar
484,16/17,LaLiga,22,02/11-17,A,FC Barcelona,Deportivo Alaves,0:06,RW,59,0:03,Left-footed shot,Neymar

In [31]:
df.sort_values("Minute",ascending=True)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
253,Dec-13,LaLiga,1,8/19/12,H,FC Barcelona,Real Sociedad,5:01,CF,10,2:01,Left-footed shot,Pedro
283,Dec-13,Copa del Rey,last 16,12/12/12,A,FC Barcelona,CÃ³rdoba CF,0:02,CF,10,0:01,Left-footed shot,David Villa
30,07/08,LaLiga,5,9/26/07,H,FC Barcelona,Real Zaragoza,4:01,RW,10,2:01,Left-footed shot,Deco
194,11-Dec,LaLiga,8,10/15/11,H,FC Barcelona,Racing Santander,3:00,CF,11,1:00,Right-footed shot,Andres Iniesta
236,11-Dec,UEFA Champions League,Quarter-Finals,04-03/12,H,FC Barcelona,AC Milan,3:01,RW,11,1:00,Penalty,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,19/20,LaLiga,28,6/13/20,A,FC Barcelona,RCD Mallorca,0:04,RW,90+3,0:04,Right-footed shot,Luis Suarez
399,14/15,LaLiga,32,4/18/15,H,FC Barcelona,Valencia CF,2:00,RW,90+4,2:00,Left-footed shot,NaN
565,18/19,LaLiga,12,11/11-18,H,FC Barcelona,Real Betis Balompie,3:04,SS,90+4,3:04,Left-footed shot,Arturo Vidal
466,16/17,LaLiga,9,10/22/16,A,FC Barcelona,Valencia CF,2:03,RW,90+4,2:03,Penalty,NaN
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,4:3,Direct free kick,\t

In [36]:
df.rename(columns={"Result":"FT"},inplace=True)
df

,Season,Competition,Matchday,Date,Venue,FC,Opponent,FT,Playing_Position,Minute,At_score,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,2:00,Left-footed shot,Ronaldinho Gaacho
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,3:00,Left-footed shot,NaN
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,2:00,Left-footed shot,Samuel Etoo
3,05/06,LaLiga,19,1/15/06,H,FC Barcelona,Athletic Bilbao,2:01,RW,50,2:01,Left-footed shot,Mark van Bommel
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,2:00,Left-footed shot,Ronaldinho Gaacho
...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,22/23,Ligue 1,21,2/1/23,A,Paris Saint-Germain,Montpellier HSC,1:3,SS,72,0:2,Left-footed shot,Fabián Ruiz
700,22/23,Ligue 1,22,2/4/23,H,Paris Saint-Germain,FC Toulouse,2:1,SS,58,2:1,Left-footed shot,Achraf Hakimi
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,4:3,Direct free kick,\t
702,22/23,Ligue 1,25,2/26/23,A,Paris Saint-Germain,Olympique Marseille,0:3,CF,29,0:2,Right-footed shot,Kylian Mbappé
703,22/23,Ligue 1,26,3/4/23,H,Paris Saint-Germain,FC Nantes,4:2,CF,12,1:0,Left-footed shot,NaN

In [37]:
df.drop("At_score",axis=1)

,Season,Competition,Matchday,Date,Venue,FC,Opponent,FT,Playing_Position,Minute,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,Left-footed shot,Ronaldinho Gaacho
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,Left-footed shot,NaN
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,Left-footed shot,Samuel Etoo
3,05/06,LaLiga,19,1/15/06,H,FC Barcelona,Athletic Bilbao,2:01,RW,50,Left-footed shot,Mark van Bommel
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,Left-footed shot,Ronaldinho Gaacho
...,...,...,...,...,...,...,...,...,...,...,...,...
699,22/23,Ligue 1,21,2/1/23,A,Paris Saint-Germain,Montpellier HSC,1:3,SS,72,Left-footed shot,Fabián Ruiz
700,22/23,Ligue 1,22,2/4/23,H,Paris Saint-Germain,FC Toulouse,2:1,SS,58,Left-footed shot,Achraf Hakimi
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,Direct free kick,\t
702,22/23,Ligue 1,25,2/26/23,A,Paris Saint-Germain,Olympique Marseille,0:3,CF,29,Right-footed shot,Kylian Mbappé
703,22/23,Ligue 1,26,3/4/23,H,Paris Saint-Germain,FC Nantes,4:2,CF,12,Left-footed shot,NaN

In [43]:
df.drop([0,3]).head()

,Season,Competition,Matchday,Date,Venue,FC,Opponent,FT,Playing_Position,Minute,At_score,Type,Goal_assist
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,3:00,Left-footed shot,NaN
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,2:00,Left-footed shot,Samuel Etoo
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,2:00,Left-footed shot,Ronaldinho Gaacho
5,05/06,LaLiga,21,1/29/06,A,FC Barcelona,RCD Mallorca,0:03,CF,75,0:02,Right-footed shot,Sylvinho
6,05/06,LaLiga,21,1/29/06,A,FC Barcelona,RCD Mallorca,0:03,CF,83,0:03,Left-footed shot,Ronaldinho Gaacho

In [44]:
df.isnull()

,Season,Competition,Matchday,Date,Venue,FC,Opponent,FT,Playing_Position,Minute,At_score,Type,Goal_assist
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,False,False,False,False,False,False,False,False,False,False,False,False,False
700,False,False,False,False,False,False,False,False,False,False,False,False,False
701,False,False,False,False,False,False,False,False,False,False,False,False,False
702,False,False,False,False,False,False,False,False,False,False,False,False,False
703,False,False,False,False,False,False,False,False,False,False,False,False,True

In [45]:
df.isnull().sum()

Season                0
Competition           0
Matchday              0
Date                  0
Venue                 0
FC                    0
Opponent              0
FT                    0
Playing_Position      0
Minute                0
At_score              0
Type                  1
Goal_assist         214
dtype: int64

In [46]:
df.fillna(0)

,Season,Competition,Matchday,Date,Venue,FC,Opponent,FT,Playing_Position,Minute,At_score,Type,Goal_assist
0,04/05,LaLiga,34,05-01/05,H,FC Barcelona,Albacete Balompie,2:00,CF,90+1,2:00,Left-footed shot,Ronaldinho Gaacho
1,05/06,UEFA Champions League,Group Stage,11-02/05,H,FC Barcelona,Panathinaikos Athens,5:00,RW,34,3:00,Left-footed shot,0
2,05/06,LaLiga,13,11/27/05,H,FC Barcelona,Racing Santander,4:01,RW,51,2:00,Left-footed shot,Samuel Etoo
3,05/06,LaLiga,19,1/15/06,H,FC Barcelona,Athletic Bilbao,2:01,RW,50,2:01,Left-footed shot,Mark van Bommel
4,05/06,LaLiga,20,1/22/06,H,FC Barcelona,Deportivo Alaves,2:00,CF,82,2:00,Left-footed shot,Ronaldinho Gaacho
...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,22/23,Ligue 1,21,2/1/23,A,Paris Saint-Germain,Montpellier HSC,1:3,SS,72,0:2,Left-footed shot,Fabián Ruiz
700,22/23,Ligue 1,22,2/4/23,H,Paris Saint-Germain,FC Toulouse,2:1,SS,58,2:1,Left-footed shot,Achraf Hakimi
701,22/23,Ligue 1,24,2/19/23,H,Paris Saint-Germain,LOSC Lille,4:3,CF,90+5,4:3,Direct free kick,\t
702,22/23,Ligue 1,25,2/26/23,A,Paris Saint-Germain,Olympique Marseille,0:3,CF,29,0:2,Right-footed shot,Kylian Mbappé
703,22/23,Ligue 1,26,3/4/23,H,Paris Saint-Germain,FC Nantes,4:2,CF,12,1:0,Left-footed shot,0

In [51]:
data={"id":[1,2],
      "name":["john","david"]}
df1=pd.DataFrame(data)
df1

   id   name
0   1   john
1   2  david

In [55]:
data1={"id":[1,2],
      "marks":[45,70]}
df2=pd.DataFrame(data1)
df2

   id  marks
0   1     45
1   2     70

In [59]:
pd.merge(df1,df2,on="id")

   id   name  marks
0   1   john     45
1   2  david     70

In [61]:
df=pd.DataFrame({"marks":[50,60,70,80]})
df["marks"]=df["marks"].apply(lambda x:x+5)
df

   marks
0     55
1     65
2     75
3     85